package application.controllers;

import application.Admin;
import javafx.fxml.FXML;
import javafx.scene.control.Label;
import javafx.scene.input.SwipeEvent;

public class AdminDashboardController {
	private Admin admin;
		
	@FXML
	private Label adminUsername;
	
    public AdminDashboardController(Admin admin) {
        this.admin = admin;
    }
    
    // The initialize() method is called after the FXML is loaded and fields are injected
    @FXML
    public void initialize() {
        // Set the admin username in the Label after FXML fields are injected
        if (admin != null && adminUsername != null) {
            adminUsername.setText("Username: " + this.admin.getName());
        }
    }
    
	// Event Listener on VBox.onSwipeLeft
	@FXML
	public void buttonControl(SwipeEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox.onSwipeLeft
	@FXML
	public void buttonControl(SwipeEvent event) {
		// TODO Autogenerated
	}
}
