package application.UI;

import javafx.fxml.FXML;

import javafx.scene.input.SwipeEvent;

public class OrgRepDashboardController {

	// Event Listener on VBox.onSwipeLeft
	@FXML
	public void buttonControl(SwipeEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox.onSwipeLeft
	@FXML
	public void buttonControl(SwipeEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on VBox.onSwipeLeft
	@FXML
	public void buttonControl(SwipeEvent event) {
		// TODO Autogenerated
	}
}
